/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doolhof;

import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Ian
 */
public class Basisspel extends javax.swing.JPanel implements SpelListener{

    private final static int HOOGTE = 15;
    private final static int BREEDTE = 20;
    private List<Veld> speelVeld = new ArrayList<>();
    private Spelstatus spelstatus;
    
    /**
     * Creates new form Basisspel
     */
    public Basisspel() {
        initComponents();
    }
    
    public void BouwSpelveld(String[][] layout)
    {
        
        for (int i = 0; i < HOOGTE; i++) {
            for (int j = 0; j < BREEDTE; j++) {
                Veld veld = new Veld(j,i);
                System.out.println("i="+i+" j="+j);
                if("m".equals(layout[i][j]))
                {
                    Muur muur = new Muur(veld, this);
                    veld.setSpelelement(muur);
                }
                if("s".equals(layout[i][j]))
                {
                    Speler speler = new Speler(veld, this);
                    veld.setSpelelement(speler);
                }
                
                
                speelVeld.add(veld);
                
            }
            
        }
        
        for (int i = 0; i < speelVeld.size(); i++) {
            Veld veld = speelVeld.get(i);
            int boven = i - 20;
            int onder = i + 20;
            int rechts = i + 1;
            int links = i - 1;
            
            if(indexExists(speelVeld, boven)){
                veld.setBuur(Richting.NOORD, speelVeld.get(boven));
            }
            if(indexExists(speelVeld, onder)){
                veld.setBuur(Richting.ZUID, speelVeld.get(onder));
            }
            
            if(indexExists(speelVeld, rechts)){
                System.out.println("rechst okay");
                veld.setBuur(Richting.OOST, speelVeld.get(rechts));
            }
            
            if(indexExists(speelVeld, links)){
                veld.setBuur(Richting.WEST, speelVeld.get(links));
            }
        }
        addKeyListener(getSpeler());
        setSpelstatus(Spelstatus.GESTART);
        repaint();
    }
    public boolean indexExists(final List list, final int index) {
    return index >= 0 && index < list.size();
}
    public Veld getVeld(int x,int y){
        for(Veld veld: speelVeld){
		if(veld.getxPos() == x){
		    if(veld.getyPos() == y) {
                        return veld;
                    }            
		}
	    }
        return null;
    }
    @Override
    public void paintComponent(Graphics g){
	super.paintComponent(g);
	
	for ( Veld veld: speelVeld){
	   veld.tekenVierkant(g);
	}
    }
    
     @Override
    public void setSpelstatus(Spelstatus spelstatus) {
        this.spelstatus = spelstatus;
    }

    @Override
    public Spelstatus getSpelstatus() {
        return spelstatus;
    } 
    private Speler getSpeler(){
	    for(Veld veld: speelVeld){
		if(veld.getSpelItem() instanceof Speler){
		    return(Speler) veld.getSpelItem();               
		}
	    }
       return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
